version: '2'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      CONFIG_FILE: ${WIKIJS_CONFIG_FILE}
    restart: unless-stopped
    ports:
      - 3000
      - 3443

volumes:
  db-data:
    # specifying the name explicitly as a workaround bug https://github.com/portainer/portainer/issues/1989
    name: "db-data"